### ISSUE TITLE
compute_entry_status is never producing EntryDhtStatus::Rejected

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain#1147]
https://github.com/holochain/holochain/blob/51dbcced87252c7b34917056ee34cbddada0e918/crates/holochain_state/src/query/entry_details.rs#L173-L184

Is this the intended behaviour? 

I am trying to make sense of, and use, actual implications for an entry failing validation

**Comment by Connoropolous** [comment]
@abe-njama In this document, I came up with this, while trying to pre-evaluate what happens to rejected DHT elements. 
https://hackmd.io/Vz9feiycSOGYmV7jDLH7ww

I am hoping for some comment from the team on what, at the moment, the key behaviors around invalidated/rejected elements are.

**Comment by freesig** [comment]
Yeh this is a good point. It should really check if there are no valid headers and there are some rejected headers then the current status would be rejected. Keep in mind this status would go back to valid as soon as there was one valid header.

**Comment by freesig** [comment]
I had a look over the hackmd. It's probably worth noting that an entry can never really be rejected. The `EntryDhtStatus` was written a long time a go and should probably be updated.
Only headers can be rejected because there can always be a future header that makes an entry valid.
If the entry fails app validation because of something actually in the entry's content then no valid header will ever exist but there's no way to actually prove that.

**Comment by Connoropolous** [comment]
Does this confirm the general theorem that there are currently no repercussions around invalid headers, out of the box?
Is it for each app developer to handle according to requirements/preferences?

**Comment by freesig** [comment]
Yes until warrants are implemented there are no repercussions except that no authority will return a rejected header to a regular get.

**Comment by Connoropolous** [comment]
"no authority will return a rejected header to a regular get."
Oh, it wont? 
In my diving the code I couldn't find any logic to that effect, any chance you could point me at something?
