### ISSUE TITLE
schedule can pass in a payload wit h the scheduler function

### ISSUE THREAD

**Issue by zo-el** [holochain/holochain#1656]
This is a suggestion for the holochain team.
```rust
hdk::prelude::schedule("clean_up_task", {payload: "task-id"});
```

Being able to pass a payload in a scheduled function will be very useful when you need to trigger a scheduled task for a very specific reason based on different conditions.

Is this possible? and would like to hear your thoughts on this topic

**Comment by jost-s** [comment]
I can't comment on the feasibility. I can see the general usefulness of such a feature.

**Comment by pdaoust** [comment]
I see this hasn't gotten any attention in the last 28 days. For those who have access to the Holo HackMD, [this design doc](https://hackmd.io/@hololtd/BJ6Ch-TZK?type=view) explains it a bit more. For those who don't have access, it appears to create a risk of the 'confused deputy problem' if an arbitrary zome call is allowed to pass potentially malicious args on to a privileged function without having to show a valid capability.

It could be argued that, if a caller has a capability, then the grantor understands the risks and is indeed granting the privilege of being able to schedule a function with arbitrary args. I think it's also true that disallowing args from the `schedule` call (which means you can only 'pass' data to the scheduled function as existing state in the source chain or DHT) doesn't completely remove the risk. But I believe (@thedavidmeister can correct me if I'm wrong) that it removes one of the most obviously non-obvious footguns.

**Comment by thedavidmeister** [comment]
@pdaoust yes this was by design, and it's not just about the confused deputy, it's also about preventing the ability to flood the scheduler with many near identical calls like `schedule(1); schedule(2); schedule(3); ...`

it's important that the scheduler is idempotent and lightweight in terms of the overhead of dispatching what has been scheduled, the concept of what an idempotent scheduled task is becomes fuzzy when you have different inputs

same issues if we'd allow per-agent information in the dispatched task

probably what is being reached for here is some kind of local state that is not the source chain that can be read (and written to?) by scheduled tasks for the sake of coordinating things

there's more discussion in the code comments on schedule https://github.com/holochain/holochain/blob/develop/crates/hdk/src/time.rs#L68

**Comment by maackle** [comment]
Looks pretty clearly like we can't do this
