### ISSUE TITLE
[FEATURE REQUEST] Ability to get storage space of cells via conductor API

### ISSUE THREAD

**Issue by matthme** [holochain/holochain#1660]
It would be really nice if the conductor API provided a way to get the storage space associated to hApps and cells.

**Comment by matthme** [comment]
What the Launcher does is really just the "bare minimum", i.e. reading the total size of the conductor directory on the filesystem. What I would like is that there is an API to get the size for each App/Cell separately. This would give me as an end-user a way better understanding on how the total storage comes about, i.e. which apps/cells are "storage-hungry" and might be worth deleting etc. Having this fine-grained information would require access to the database I assume, i.e. it would need to be provided by the conductor.

**Comment by ThetaSinner** [comment]
Great, that makes sense. The databases are broken down by cell on disk so  I think you could track it back to the app but I agree that this is something that the conductor should understand and provide rather than another application looking directly at its data storage implementation.

I'll see what can be done for this

**Comment by ThetaSinner** [comment]
@matthme Does https://github.com/holochain/holochain/pull/2147/files#diff-4ee7d77645a329c52e7cec0620a09f310951984156d711834f98dede142dac87R427 look like it would give you the information you need? I'm still working through the changes so it's a WIP but it'd be good to check it's going in a useful direction :)

**Comment by ThetaSinner** [comment]
Okay that's useful. I've included the cache db in the linked PR. Yes the conductor and wasm databases are 'global' to the [conductor](https://github.com/holochain/holochain/blob/develop/crates/holochain/src/conductor/space.rs#L82) where the others are scoped to the [application](https://github.com/holochain/holochain/blob/develop/crates/holochain/src/conductor/space.rs#L98).

I want to think a bit harder about how to surface the wasm storage at least, because it would be nice to know the breakdown of that by app too ideally. I'll proceed with the current PR but won't close this issue until we address that too

**Comment by jost-s** [comment]
With what Michael explained in mind, it's not possible to show a clear cut breakdown of storage by application. Maybe displaying storage by cell would be of little use, because you'd have to be a knowledgeable end-user to know what a cell is, and secondly there's no way to delete a cell from the Launcher.

Perhaps something in-between a per-DNA and per-App reporting would be the right tradeoff between accuracy and practicality. The per-DNA reporting that Michael suggests, but perhaps with the app at the top level instead of the DNA. This is meant for an end-user, not a hApp dev, so DNA means nothing to them.

**Comment by maackle** [comment]
This might be a situation where the actual reality is too complicated for the user to make sense of, but at the same time is too fundamental to be ignored or simplified, so that we may have to give them a more targeted interface that answers a specific question, rather than a more general interface where they can answer multiple questions.

If the question is, "what should I do to free up space?", then we can give them a view that tries to answers exactly that. We don't need to use the name "DNA" at all: instead we can represent apps as having shared storage. We can perhaps get a list of all DNAs in descending order of size, along with the apps using that DNA. Then, for DNAs with the exact same set of apps associated and no other associated apps (a common case when the same app is duplicated multiple times), we can combine the totals into a blob of "shared storage" of a certain size. After this merging, the user would see a list of "chunks of disk space" listed in descending order, and along with each, a list of apps that would need to be uninstalled in order to free that much space. There could even be a button to uninstall those apps en masse. I think that would be an effective and entirely accurate UX for finding out what I need to do to free up space.

Or something else along these lines. I just want to encourage thinking about UX that can be sensible without sacrificing accuracy, even if unconventional.

The interface could be per-App if there were a good way to highlight when two apps share (some portion of) the same disk space.

**Comment by matthme** [comment]
> and secondly there's no way to delete a cell from the Launcher

That's actually not true for cloned cells. They can be deleted in the Launcher, provided that they have been disabled via the app websocket earlier (if the app's UI offers that functionality). It would also be possible to have enabled cloned cells be deletable in the Launcher (but not implemented currently), however that might lead to inconsistent behavior in the app's UI. Thinking about it now, it might still be desirable to have the ability to delete an enabled cloned cell independently of the UI.

**Comment by ThetaSinner** [comment]
Lots of good ideas here thanks. I think ensuring no duplicates is super important so that a simple sum over what is given back tells you how much storage is being used by the conductor.

It sounds like no matter how we organise it, it's not going to make sense to ask 'how much storage space is my app using' except in simple scenarios. Because other use of our 'blobs' can cause data to be stored that we can't see or control. In which case I'll drop the 'get for this app' version of the query.

For the 'get all' case I like the idea of organising by 'blobs' where each blob has a size and a list of applications that are using that blob. That feels like it's the clearest way to describe that the app doesn't necessarily 'own' the blob. 
It could be organised by app with each blob having an id that is the same across all apps and the result would be effectively the same but it might be slightly more confusing to work with as a consumer. A consumer who really does want to know roughly what storage their application is using can filter the blobs by blobs which are being used by their app and get an approximate answer.

If this sounds okay I'll take another pass at the change

**Comment by maackle** [comment]
I think the breakdown into parts is helpful for sure.

I like where you're going with the "blobs". Using IDs does sound cumbersome. And filtering by app sounds useful -- it would tell you what other apps you need to delete in addition to the one you filtered by to free that blob. So this view can easily answer at least two questions: "Are there any super hungry apps that I can delete?" and "How much space can I clear up by deleting *this* app (and all of its 'cousins')?"

**Comment by jost-s** [comment]
You can return storage taken up by authored/cache/dht individually, but for user display in the Launcher I would aggregate them.

**Comment by ThetaSinner** [comment]
This change has now reached the clients for Rust (thank you @jost-s) https://github.com/holochain/holochain-client-rust/commit/6ed876a6060fed41d049966f32e1ae7f5b342b12
and for js https://github.com/holochain/holochain-client-js/commit/28448d1e85d4975030443b209a8d0a6d515eb6c4

Are you happy for this to be closed @matthme or would you like a chance to try it out first?

**Comment by ThetaSinner** [comment]
Closing as complete for now, please open a new issue if there are any problems with this
