### ISSUE TITLE
Addition of `authorizeSigningCredentials` breaks ability for sandboxed hApps to initialise dynamically

### ISSUE THREAD

**Issue by pospi** [holochain/holochain#1746]
**Describe the bug**

Before the beta RC we were able to initialise connections to our app without access to the admin websocket. It now seems that after `hc s call install-app [...]` there is an additional step for `authorizeSigningCredentials` which the sandbox CLI does not expose.

@Connoropolous has made some [changes to our connection logic](https://github.com/h-REA/hREA/pull/376/commits/7b3e07d005d232d307a89660715ffef4034bb11f) to work around this, but given that such a workaround necessitates use of the admin websocket it does not seem like a feasible long-term solution for standard Holochain apps.

**Expected behavior**

We should be able to provision everything we need for a hApp to operate via the sandbox tools, before initialising a client app and connecting to the app websocket (only).

Present in `holochain_cli 0.1.0-beta-rc.2`.

**Comment by abe-njama** [comment]
@jost-s @thedavidmeister @maackle should we prioritize this for Beta release. What are your thoughts on this issue?

**Comment by guillemcordoba** [comment]
@pospi this is exactly the reason why @matthme built `hc launch`, which is already available and working in the latest holonix. I hope this addresses what you want... Let me know.

Here you can see how the scaffolding tool uses it instead of `hc sandbox` (which it is using underneath): https://github.com/holochain/scaffolding/blob/db3096289691f88f505f1f5e3a61415dd4ab2e24/templates/lit/web-app/package.json.hbs#L12

**Comment by Connoropolous** [comment]
thanks @guillemcordoba 
we will look into that. I had no idea about the exact purpose or nature of `hc launch`

**Comment by Connoropolous** [comment]
we don't have the ability to access the new launcher yet though so I doubt we can do anything with it. It's fine we can wait till it's released

**Comment by Connoropolous** [comment]
oh, I see. cool!

**Comment by jost-s** [comment]
@pospi @Connoropolous Does this address the issue?

**Comment by Connoropolous** [comment]
we will see. It's hard to visualize without trying it

**Comment by jost-s** [comment]
ah sure, okay, I'll wait for an answer first

**Comment by pospi** [comment]
Sounds very promising though! Thanks everyone

**Comment by Connoropolous** [comment]
I am just getting some exposure to `hc launch` working with Wesley on something around the We app. Will report back...

**Comment by pospi** [comment]
@matthme as per the referenced issue, my first query here is whether `hc launch` can run a headless Holochain conductor that other local development processes can connect to from outside? Otherwise we are foregoing developer ergonomics...

**Comment by matthme** [comment]
@pospi I recently added support for using it pointing to a dev-server running on localhost: https://github.com/holochain/launcher/pull/119. Is this already what you need? It's already in holonix so you should be able to test it out.

If that's not enough, I think I need to understand better what you need exactly, i.e. what you mean with a "headless conductor". The point about `hc launch` is that it provides the combination of `conductor + lair-keystore + tauri window` so that it can make zome call signing without the need for a hApp to make a call to the admin websocket via `authorizeSigningCredentials`.

**Comment by Connoropolous** [comment]
seems, still untested, to be very much what is needed. Leaving this open for now but thanks for all the support! We haven't tried it yet

**Comment by pospi** [comment]
That sounds mostly-perfect @matthme. My only lingering discomfort is at a political level (I hadn't heard of Tauri before)-

> WebKit on macOS, WebView2 on Windows and WebKitGTK on Linux

I *would* like to retain the ability to do Gecko-based rendering tests and be supporting a browser runtime with a featureset that is not directed by corporate interests. Especially with [renewed interest](https://servo.org/blog/2023/01/16/servo-2023/) in the Servo project in the news recently.

Would the outcome with `hc launch` be that *only* the privileged `tauri` window has access to the conductor appWebsocket? Or should I still be able to access my dev UIs directly in the browser as well?

**Comment by pospi** [comment]
> tauri windows at least for now

I really hope it's temporary. The debugging experience in Tauri is pretty limiting- even with sourceMaps correctly configured it doesn't apply those when debugging, meaning you can't really inspect variables or dynamically execute code and have to guess which of the minified variable names corresponds to those visible in the 'Sources' window.

**Comment by matthme** [comment]
This is likely because you use a dev setup that does not make use of hc launch's localhost capabilities. Check out the example generated by `hc scaffold example forum`. It uses a vite dev server and then the `--ui-port` argument of hc launch which makes the code perfectly readable.
I see however that even in this mode the dev experience is probably inferior to what one would have in a browser.

**Comment by pospi** [comment]
> likely because you use a dev setup that does not make use of hc launch's localhost capabilities

In terms of HMR, yes 100%! :slightly_smiling_face: 

In terms of debugging experience, that's consistently limiting no matter what UI tooling you might bring into that Tauri window. Its devtools just aren't at feature parity with what Firefox or Chromium offer- FWIW there isn't any websocket frame debugging either.
Could be a platform issue, no idea if Tauri has different / better devtools on Windows/OSX than on Linux.

**Comment by Connoropolous** [comment]
I just want to note that the signing credentials are portable, so you could acquire them in one context, and then bring them over to another and make authorized calls

**Comment by matthme** [comment]
Can you elaborate on what you mean by "another context"? I just tried to come up with the possible contexts I can think of and they are

1. another UI than the one the credentials have initially been created for but managed by the same process that has admin access
2. another process than the one that has admin access and that created the credentials
3. a remote peer

1 and 2 are probably possible, 3 I would guess not but I'm not 100% sure.

**Comment by maackle** [comment]
Chiming to say I also hope we don't get locked in to a particular UI context. My vague understanding, which could be wrong since I don't follow the UI/launcher side of things as closely as I'd like, is that we've leaned heavily on Tauri and consolidated a lot of functionality into that implementation in the name of speed and security and ensuring a good UX, and we would do well to eventually generalize this to allow `hc` and other tools to do the same, for a better dev experience, but that might require extra thought on the security front. Or perhaps `hc` could run a less secure dev mode that allows any browser but doesn't guarantee security?

**Comment by harlantwood** [comment]
I believe clutter is doing the manual work to make it work in a normal browser here:

https://github.com/artbrock/clutter/blob/0ce71ae32c612f6b3e7920c202ed321469a15bb6/ui/src/main.ts#L83

cc @jost-s @pospi @Connoropolous

**Comment by harlantwood** [comment]
Hmm, when I posted the above comment in discord, @guillemcordoba responded: 

![E1FAD872-C5D2-4FA2-9A42-D870DEEAF4DF](https://user-images.githubusercontent.com/38769/224346525-eb539413-f70a-433f-b201-7e8f3573de6f.jpeg)

@matthme @maackle do you know that that mechanism will be, or what is likely?

**Comment by ThetaSinner** [comment]
I believe the solution to this would be to use one of the Holochain clients (JS or Rust) to prepare a connection.

We should document how this is done, and how the launcher does it. @ThetaSinner to open a docs-pages issue about this

**Comment by jost-s** [comment]
headless nodes and zome call signing are valuable features, but not right now on our list of priorities. Closing this to see which pull comes up.
