### ISSUE TITLE
[BUG] Including a line break in integrity zome function defintion changes wasm binary

### ISSUE THREAD

**Issue by mattyg** [holochain/holochain#1964]
**Describe the bug**
Including a line break in an integrity zome function definition changes the wasm binary, and so the DNA hash.

For example, if you have two identical dnas with only the following differences, they will build to different wasm binaries.

(without line break)
```rust
#[hdk_extern]
pub fn genesis_self_check(data: GenesisSelfCheckData) -> ExternResult<ValidateCallbackResult> {
    Ok(ValidateCallbackResult::Valid)
}
```

(with line break)
```rust
#[hdk_extern]
pub fn genesis_self_check(
    data: GenesisSelfCheckData
) -> ExternResult<ValidateCallbackResult> {
    Ok(ValidateCallbackResult::Valid)
}
```

**Expected behavior**
Inclusion or exclusion of a line break is functionally equivalent in Rust, so should not affect the wasm binary.

**System information:**
 - OS: ubuntu 22.04
 - Browser [e.g. chrome, safari]: n/a
 - Holochain and HDK Version:  0.1.3

**Steps to reproduce**
Minimal reproduction: https://github.com/mattyg/bug-reproduction-linebreak
(execute the `run-tests.sh` script to see the different wasm binary hashes)

**Screenshots**
n/a

**Additional context**

I guess a simple workaround would be to run rustfmt before doing cargo builds. I imagine this issue could be upstream of holochain.

Also I realized if I run wasm2wat on the two differing zome builds they produce identical .wat outputs. Not sure if that's helpful.

**Comment by maackle** [comment]
This sounds more like an issue with rustc compilation of the `wasm32-unknown-unknown` target that you could take up with the Rust team. The Holochain conductor ultimately isn't concerned with how devs build their wasms, although we do provide extensive tooling to help them build them using Rust. The fact that rust changes wasm output because of a newline is not something we can really help.

Indeed it sounds like formatting code before compilation is the best solution. We do want to support deterministic builds given some fixed source code, but it's a slippery slope to supporting determinism across certain edits (should comments be excluded too, since they don't get executed? What about dead code, which also *shouldn't* affect bytecode output, but might anyway?)

**Comment by mattyg** [comment]
Yeah that all makes perfect sense. Thanks for the context.

**Comment by mattyg** [comment]
> @maackle do you see it as in-scope to document this expectation anywhere in our repo or the developer docs?
> 
> @mattyg something i'm curious about is whether a roundtrip to [the Wasm text format](https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format) and back into binary form resolves this issue.

Yes, if I run wasm2wat to generate a .wat, and then run wat2wasm to generate a wasm again, the hashes are identical. Different from both of the *original* dna hashes, but identical to each other.
