### ISSUE TITLE
Allow for enum variants in hdk_link_types

### ISSUE THREAD

**Issue by dauphin3** [holochain/holochain#2118]
It might be handy to have multiple link types beyond just unit

for ex:

`#[hdk_link_types]
pub enum LinkTypes {
  ExampleVariant(One),
  AnotherExample(Two)
}`

would this possible without breaking too much?

**Comment by ThetaSinner** [comment]
Hi @dauphin3,

Could you give me an idea what the use case is for this?

My initial thoughts are that the variants might be best represented as seperate link types. Say you have a music app where you can have links from Artist to Single or Album. Then rather than having an 'ArtistOwned(Kind)' enum constant which describes the target type with `Kind`, you could have two different link types for `ArtistOwnedSingle` and `ArtistOwnedAlbum`.

Just guessing here though without knowing what the use case is!
