### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dukejones** [holochain/holochain#2229]
**Describe the bug**
Using sweettest on beta 2 rc 3, I include `holochain` as a dev-dependency (probably sweettest should be broken out into a standalone crate soon, but that's another issue)

**Expected behavior**
`cargo clean && cargo test` compiles smoothly and runs the sweettest

**System information:**
 - OS: Mac ARM M1
 - Browser n/a
 - Holochain and HDK Version (run `hn-introspect` as well as `holochain --build-info`
 from the nix shell and paste output)
```
holochain (holochain 0.1.3): ed5b7bb461c2a8bfd4d2633bad604a20b8f2da03
lair-keystore (lair_keystore 0.2.3): cbfbefefe43073904a914c8181a450209a74167b
hc-launch (holochain_cli_launch 0.0.12): 1ad188a43900c139e52df10a21e3722f41dfb967
hc-scaffold (holochain_scaffolding_cli 0.1.7): c245d306110f3a5408f1dbe15d6a3725884ef3f4
{"git_info":null,"cargo_pkg_version":"0.1.3","hdk_version_req":"0.1.1","hdi_version_req":"0.2.1","timestamp":"2023-03-31T18:31:29.933760Z","hostname":"static.224.140.132.142.clients.your-server.de","host":"aarch64-apple-darwin","target":"aarch64-apple-darwin","rustc_version":"rustc 1.66.1 (90743e729 2023-01-10)","rustflags":"","profile":"release"}
```

**Actual Behavior**
```
error[E0599]: no variant named `Quic` found for enum `TransportConfig`
  --> /Users/dukejones/work/Holochain/deepkey/.cargo/registry/src/github.com-1ecc6299db9ec823/holochain-0.2.0-beta-rc.3/src/sweettest/sweet_conductor_config.rs:72:73
   |
72 |             network.transport_pool = vec![kitsune_p2p::TransportConfig::Quic {
   |                                                                         ^^^^ variant not found in `TransportConfig`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `holochain` due to previous error
```

**Steps to reproduce**

In Cargo.toml:
```toml
[workspace.dependencies]
serde = "1"
hdi = { version = "0.3.0-beta-rc.3" }
hdk = { version = "0.2.0-beta-rc.3" }
holochain = { version = "0.2.0-beta-rc.3", default-features = false, features = [ "test_utils" ] }
```

**Mitigation**
Adding `features = "tx5"` like so:
```toml
holochain = { version = "0.2.0-beta-rc.3", default-features = false, features = [ "test_utils", "tx5" ] }
```

**Additional context**
It looks like the issue is on `holochain/holochain/crates/holochain/src/sweettest/sweet_conductor_config.rs:70`

**Comment by ThetaSinner** [comment]
Hi @dukejones, thank you for the report!

This issue of what features can be enabled/disabled came up on another issue recently. `tx5` is a default feature from `0.2` which means this should build if you include default features. As you've spotted though, `test_utils` is also required for `holochain` to build so disabling default features comes with a couple of surprises. In the case of sweetest it shouldn't be possible to enable code that doesn't compile though so I'll take a look at that.

It would be useful to understand why you are disabling default features, is this because you're just wanting to pull in sweetest and as little else as possible? If so I expect that splitting sweetest into its own crate would help with that?

One more thing, I'm not sure how stable you'll find using `holonix` with `0.2` release candidates. For example, the default kitsune transport switching from quic to webrtc (tx2 -> tx5) should work against a `0.1.3` conductor but work has gone into webrtc in the `0.2` release. The `0.2` release was cut last night so pending testing that should be making its way to holonix soon - at that point upgrading your deps should be safe 😃

**Comment by ThetaSinner** [comment]
@dukejones I've just done a quick check that building with `default-features=false` and `features = ["test_utils"]` is okay on the development version. This change should appear in the `0.2` release candidate 5

**Comment by dukejones** [comment]
Thanks! Yes exactly, I was just trying to pull in the absolute minimum to be able to use sweettest to test my zomes.

**Comment by ThetaSinner** [comment]
The next release on `0.1` (which will be `0.1.5) adds a new feature `sweetest` which hides these details. You should be able to consume holochain without default features and just that feature flag for this use case.
