### ISSUE TITLE
[Enhancement] Performance / Usability improvements for cell startup workflow

### ISSUE THREAD

**Issue by mattyg** [holochain/holochain#2414]
Currently it takes ~15-20 seconds to startup a cell (at least on my 5 year old mid-range laptop). I believe this is because the startup process includes setting up network connections initiating gossip (though I'm not positive, I haven't looked into the codebase).

I was thinking one lower-effort performance / usability improvement for cell startup time could be to use something like the stale-while-revalidate pattern in front-end development. When the cell starts, it immediately becomes available over the app interface for serving data it already has in its local database. Then once networking comes online it can start making requests to the dht and gossiping.

**Comment by matthme** [comment]
I also just looked at this because starting up the conductor takes painfully long. A conductor with ~10 apps installed takes around 1 minute to start up on my pretty decent laptop. I looked a bit into it and the bottleneck is very clearly loading wasms into memory, i.e. [this](https://github.com/holochain/holochain/blob/206ff337b38bd6eb556c71c6506f98602e882709/crates/holochain/src/conductor/conductor.rs#L576) function.
It surprises me how this can take so long, is this an sqlite limitation? I can easily load 100 3MB wasms into memory with `std::fs::read` in less than a second so I have a hard time to understand how it can take minutes to do the same by reading it from sqlite...

**Comment by matthme** [comment]
I actually think this is a pretty serious issue because it likely scales roughly linearly. So any use cases like the launcher or [We](https://github.com/lightningrodlabs/we) where the list of installed apps is expected to go way beyond 10 apps on a conductor, startup times will reach minutes, on old PCs potentially 10s of minutes.

**Comment by matthme** [comment]
Adding some activity for it not be marked stale as it's still very relevant.

**Comment by ThetaSinner** [comment]
I'm keen to re-check this following the wasmer changes. The local cache should make a big difference but we also found a nasty bug with our tracing instrumentation during app installs and startup which was costing 9s on my system. That should dramatically reduce cell startup times I think. So once we get those changes landed let's check this is still a problem.

I think this idea could work but the consequences of allowing cells to be accessed when they haven't joined the network yet may quietly break some assumptions the system makes so it's likely not a straight forward change to make :)

**Comment by jost-s** [comment]
I'm also seeing that installing an app from the local file system, using the JS client, takes unreasonably long. I'm testing this on the upcoming wasmer branch.

**Comment by jost-s** [comment]
Add a WT test for it.

**Comment by ThetaSinner** [comment]
Closing as WT issue created
