### ISSUE TITLE
Agents with Zero (Empty) arcs cannot get_links

### ISSUE THREAD

**Issue by neonphog** [holochain/holochain#2422]
@maackle @Connoropolous 

After https://github.com/holochain/holochain/pull/2352 if you set your arc to empty, then create a link and then try to get it, get_links doesn't work, possibly because the node is not an authority for its own data.

NOTE: This is a bug that could show up in sharding as well with normal adjusting arc-lengths.

See @Connoropolous notes here: https://hackmd.io/_CFnGaWvQg6Ys3DxZblmug?view#May-23

The error is generated [here](https://github.com/holochain/holochain/blob/develop/crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space/rpc_multi_logic.rs#L162-L168) after attempting a local fetch for the link which we need to make sure works.

**Comment by maackle** [comment]
I found the source of this problem: https://github.com/holochain/holochain/blob/e3fb507b0e9da3b6f6c3966a88174dcd59056d00/crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs#L941-L942

When finding local agents to route to, we're filtering by whether they hold the basis. Obviously this will be a problem for zero arcs, but also for non-full arcs, as you mention.

Ideally we can know if the basis of what we're asking for is something we authored, and then include the authoring agent in the list of local agents even if their arc doesn't cover it. @neonphog have you thought about this problem before and have any ideas, or should I just go for it?

**Comment by neonphog** [comment]
@maackle 

> have you thought about this problem before and have any ideas

only so far as to think that we *should* solve it : )

> should I just go for it?

go for it. Let me know if I can help with anything.

**Comment by Connoropolous** [comment]
@maackle this is sounding like quite a big thing to solve, do you think that’s true?

**Comment by maackle** [comment]
I've got a solution mostly worked out for this, but hit a slight snag.

I added a new Kitsune->Host call, `get_local_authors`, for any KitsuneBasis, so the rpc_multi call can find out if any local agents are holding that basis and they can be mixed in with the other agents whose arc is covering the basis. The snag is that in Holochain, a "basis" is a `AnyDhtHash` which can have a number of multihash prefixes, but in Kitsune, a `KitsuneBasis` erases the hash type, so there's no way to go from `KitsuneBasis` back to `AnyDhtHash` to query the database.

One solution is to just query for every possible type of basis, which is only 2 now but may be 3 when we add AgentPubKey as a legit basis of its own (rather than via EntryHash), but this needlessly slows down the query a bit.

Another would be to just store the main 32 bytes of the basis in the DB, but that requires a database migration. @neonphog thoughts?

**Comment by maackle** [comment]
@neonphog it's because of the line I mentioned, but here it is in context:
https://github.com/holochain/holochain/blob/e3fb507b0e9da3b6f6c3966a88174dcd59056d00/crates/kitsune_p2p/kitsune_p2p/src/spawn/actor/space.rs#L930-L951

The `local_joined_agents` in `handle_rpc_multi_as_single` is actually all not all local joined agents, but only the local agents covering the basis. That generally excludes actual authors sometimes. So my idea was to mix back in the authors of that basis if they've been filtered out.

**Comment by neonphog** [comment]
@maackle - ah, gottcha. Or, perhaps it would be fine to just not filter the local agents. It should be relatively inexpensive to make a local call like that compared to a remote network call.
