### ISSUE TITLE
[BUG] hc sandbox generate gets stuck

### ISSUE THREAD

**Issue by matthme** [holochain/holochain#2426]
**Describe the bug**
Running the following command
```
hc s --piped generate [happ name].happ --run=[port0] -a [app-id] network --bootstrap http://127.0.0.1:[port1] webrtc ws://127.0.0.1:[port2]
```
gets stuck at
```
hc-sandbox: Creating 1 conductor sandboxes with same settings
```
and then nothing further happens and no error is shown.

**Expected behavior**
The command successfully starts lair and a conductor and runs the app.

**System information:**
`hn-introspect`:
```
{"git_info":null,"cargo_pkg_version":"0.2.0","hdk_version_req":"0.2.0","hdi_version_req":"0.3.0","timestamp":"2023-04-28T11:09:57.622920606Z","hostname":"matthme-HP-Elitebook","host":"x86_64-unknown-linux-gnu","target":"x86_64-unknown-linux-gnu","rustc_version":"rustc 1.68.0 (2c8cc3432 2023-03-06)","rustflags":"","profile":"release"}
```
`lair-keystore --version`: `0.2.4`

`hc --version`: `holochain_cli 0.2.0`

**Steps to reproduce**

Run command
```
hc s --piped generate [happ name].happ --run=[port0] -a [app-id] network --bootstrap http://127.0.0.1:[port1] webrtc ws://127.0.0.1:[port2]
```
with any happ and arbitrary ports or ports from `hc run-local-services` running in another terminal. The ports don't seem to matter for the purpose of the bug.

**Comment by ThetaSinner** [comment]
Interesting one. I just fixed a similar issue where the error wasn't correctly reported on crash. I can confirm this is happening in my environment with the latest hc/holochain.

**Comment by ThetaSinner** [comment]
@matthme It looks like this is stalling because of `--piped`. It's waiting for a password from `stdin`. This should progress if you `echo 'passphrase' | ` at the front of this command. Alternatively you can drop the `--piped` and it will prompt for a passphrase.

**Comment by matthme** [comment]
Of course, that makes sense. I guess then it's not really possible to provide an error for that case, at best maybe a periodically appearing message that it's waiting for a password from stdin...

**Comment by ThetaSinner** [comment]
I've taken a longer think about this and the existing behavior is reasonable. Looking at the manual for pipes, it is expected that the read blocks while waiting for stdin to be written to. See the manual [here](https://www.man7.org/linux/man-pages/man7/pipe.7.html), the section on "I/O on pipes and FIFOs" says:

> If a process attempts to read from an empty pipe, then [read(2)](https://www.man7.org/linux/man-pages/man2/read.2.html)
       will block until data is available.  If a process attempts to
       write to a full pipe (see below), then [write(2)](https://www.man7.org/linux/man-pages/man2/write.2.html) blocks until
       sufficient data has been read from the pipe to allow the write to
       complete.

It also says that it's permitted to make the input non-blocking but common programs like `grep` and `wc` don't. E.g. running `grep "some text"` or `wc -c` will block waiting for stdin. There are places we rely on this behavior when automating the sandbox because we launch it and write to stdin later. E.g. [this(https://github.com/holochain/tryorama/blob/develop/ts/src/local/conductor.ts#L161) code] in tryorama. If we set a short timeout then we risk making tests flaky on slower machines.

I'm going to close this as won't-fix for now
