### ISSUE TITLE
[BUG] hc-scaffold-deps Nix package seems extremely slow to build?

### ISSUE THREAD

**Issue by pospi** [holochain/holochain#2685]
**Describe the bug**

I notice that Nix `building '/nix/store/8x591dca43yp5gamnjvi00jyhlg0sl0p-hc-scaffold-deps-0.1.10.drv'` seems to take a disproportionately long time to build in CI. Is anybody else experiencing this?

Builds are timing out after 1h 40m and I swear 20 minutes of that is spent waiting for `hc-scaffold-deps` to do its thing.

**Expected behavior**

Workable build speeds for larger projects under free Github CI.

**Comment by pospi** [comment]
There is not much I can tell you, I think a subsequent run has built up more caches for me but my builds are still spending ~33min total in the Nix configuration phase https://github.com/h-REA/hREA/actions/runs/5932845698/job/16099193323 and you don't get any timestamps in the terminal output.

In any case, that last run did manage to complete and those test failures look genuine rather than execution timeouts so I'm thinking this can have priority lowered for now (I don't think anyone else is building 8 DNAs and a UI in a single repository). Will let you know if I turn out to be wrong about that.

**Comment by ThetaSinner** [comment]
An upstream cache would help speed this up I think. It looks like cachix is currently set up to cache but when you take updates from upstream it will be slow. The `cachix-action` has [this](https://github.com/cachix/cachix-action/blob/master/action.yml#L8C3-L8C17) option which lets you add more read locations.

I think you could point that at `holochain-ci` which should help but unless you're doing `nix flake update` regularly it will get out of sync fairly quickly. I'm looking at splitting out a 'release' cache that will contain just the versions of Holochain that people are using rather than every version our CI produces but I don't know when that's going to be ready yet.

**Comment by ThetaSinner** [comment]
@pospi We've recently improved our cache size and maintenance so it should be smaller and contain what you need more often.

Could you try adding `holochain-ci` as an upstream cache for your builds? I'm also happy to come and make that change to see if it helps.

**Comment by c12i** [comment]
I think I can link this issue to https://github.com/holochain/scaffolding/pull/414

**Comment by ThetaSinner** [comment]
Closing, please re-open if this issue shows up again
