### ISSUE TITLE
[ENHANCEMENT] Cache cranelift builds to database / filesystem

### ISSUE THREAD

**Issue by mattyg** [holochain/holochain#2819]
**Describe the bug**
Currently the conductor is re-compiling wasms to native every time the happ is initialized in the conductor. This causes happ startup time to be unnecessarily slow (and likely contributes to the very slow launcher startup).

**Expected behavior**
Native builds should be cached in database or filesystem after the first time they are compiled. They should only be recompiled if the wasm hash has changed.

**Additional Context**
This will contribute to improving #2414 

Not sure how this will be impacted by the upcoming bump to wasmer 3

**Comment by Connoropolous** [comment]
I'm curious where/when you think you'd like to squeeze the performance gains, because (I've looked pretty deep into this) and this "They should only be recompiled if the wasm hash has changed." should already hold true. The compiled versions of the wasms are cached beyond conductor restarts, and across happs.

**Comment by mattyg** [comment]
Every time I start the conductor it logs `wasmer_compiler_cranelift::translator::func_translator: translate..` for several seconds (~15s on a small cpu vps). It still does this upon restart with the same happ. My understanding is that it's translating wasm to some intermediate language which is then translated to native machine code. I'm guessing it should only have to do this once, if it caches the result. @ThetaSinner said something at the last office hours about us not currently caching the result of this process, but I definitely don't know the details.

**Comment by Connoropolous** [comment]
"Every time I start the conductor it logs wasmer_compiler_cranelift::translator::func_translator: translate.. for several seconds (~15s on a small cpu vps). It still does this upon restart with the same happ."
that's pretty interesting. let me see if I can reproduce that with Acorn...

**Comment by mattyg** [comment]
would like confirmation if this will be resolved by https://github.com/holochain/holochain/pull/2951

**Comment by jost-s** [comment]
> would like confirmation if this will be resolved by #2951

I don't think so, that PR bumps wasmer to version 4.

**Comment by mattyg** [comment]
Oh I thought zippy said something about @thedavidmeister looking into it at the same time.

**Comment by thedavidmeister** [comment]
@jost-s @mattyg #2951 is a direct port (as close as i could) of wasmer 2.x to 4.x

so two things...

the first is to look at the wasm itself, are you running binaryen tools (specifcally wasm-opt) 

https://github.com/WebAssembly/binaryen

if you're not then there's a high chance the wasm itself is quite bloated, which will contribute to startup times.

secondly, there's actually _less_ caching in the 4.x but we have no specific performance data vs. the 2.x branch in general, it's a large refactor on the wasmer side of things

what i'm not sure on is if the slowness here is due to compiling or deserializing, if it's the former then it sounds like we're getting cache misses when we could potentially get a hit, e.g. from the database instead of memory

**Comment by mattyg** [comment]
Okay interesting thanks I'll dig into these and try to clarify what the issue is

**Comment by mattyg** [comment]
> what i'm not sure on is if the slowness here is due to compiling or deserializing, if it's the former then it sounds like we're getting cache misses when we could potentially get a hit, e.g. from the database instead of memory

Okay I reviewed the code and it looks like the wasm is compiled at runtime when time the happ is first initialized and then that built result is cached in memory. 

I would like to start caching the built result to the filesystem or database such that the wasm only needs to be compiled the *first* time the happ is initialized, persistent between conductor restarts.

**Comment by thedavidmeister** [comment]
@mattyg yeah that sounds right, i don't think we have a database backing for the serialized wasm

did you try wasm opt to make the wasm smaller?

**Comment by thedavidmeister** [comment]
this was done
