### ISSUE TITLE
[ENHANCEMENT] Conceptually clarify role_name vs clone_id for clone cells

### ISSUE THREAD

**Issue by nphias** [holochain/holochain#3219]
indexing of clones. (rolename:integer) to make a "clone_id" is undocumented and a bit unclear
I think it would be useful to have a common unique field which abstracts above all cell types (stem, clone, provisioned)
to reflect a role instance (useful for DX in the UI eg dynamic store creation) .  It could be just rolename.
the exisiting "name" field in all cells could continue to be used for user defined (optional) application logic
for example:

```
export interface StemCell {
    dna: DnaHash;
    name?: string;
    dna_modifiers: DnaModifiers;
    -> rolename: string
}
/**
 * @public
 */
export interface ProvisionedCell {
    cell_id: CellId;
    dna_modifiers: DnaModifiers;
    name?: string;
    -> rolename: string
}
/**
 * @public
 */
export interface ClonedCell {
    cell_id: CellId;
    clone_id: RoleName; -> rolename: string
    original_dna_hash: DnaHash;
    dna_modifiers: DnaModifiers;
    name?: string;
    enabled: boolean;
}
```

**Comment by nphias** [comment]
moved to https://github.com/holochain/holochain-client-js/issues/222

**Comment by mattyg** [comment]
I actually think this belongs here in the holochain repo. Makes more sense to address the confusing data structure in holochain and let that propagate to the clients. Copying my comment from that issue here:

I'm working with clone cells after a long hiatus. With fresh eyes, I'm remembering how painful I found the ergonomics:

1. Its weird that for a provisioned cell, the field is `role_name`, but for a clone cell the field is `clone_id`, even though they seem to be the same?
2. It's painful to have to conditionally check if your cell is `CellType.Provisioned` or `CellType.Cloned` every time you want to use any data within it. I would love to move all the common fields up to a higher-level object. I.e.

```
interface Cell {
  cell_id: CellId;
  name: string;
  role_name: string;
  dna_modifiers; DnaModifiers
  cell_type: CellType;
  cell_type_details: StemCell | ProvisionedCell | ClonedCell
}

```

This should probably be changed in the holochain repo rather than the client lib.

**Comment by maackle** [comment]
The cell ID is not really a role name (it's a role name plus an int). I think the bad ergonomics comes from trying to overload the role name as a cell identifier -- but only for the provisioned cell, not any of the clones, which require the clone index to be appended.

I think the struct you proposed @mattyg looks good, the only thing I would change is to create a new word for the thing that can be used to refer to a cell -- which for provisioned cells is the role name and for clone cells is role name + index -- and put that alongside the other fields, so we have both `role_name` and `new_word_meaning_an_alternate_handle_to_the_cell`

**Comment by mattyg** [comment]
@maackle That makes sense to me. Maybe we have:

`role_name: string`
`role_id: {role_name}.{u32}`

But then it feels weird that for a provisioned cell, the role_name and role_id are the same. What if the provisioned cell always used `0` as its role_id, and then the clones could be 1+? Idk maybe that makes it more confusing.

**Comment by maackle** [comment]
It's also not clear why it would be preferable to use a "role id" for a clone cell vs just using the CellId of the clone. They're both handles that you can't know beforehand, and have to query for, right?

**Comment by mattyg** [comment]
> It's also not clear why it would be preferable to use a "role id" for a clone cell vs just using the CellId of the clone. They're both handles that you can't know beforehand, and have to query for, right?

I think just for interface consistency. I.e. if i can call a provisioned cell via a role name i should be able to call a cloned cell via a role name as well.

Idk maybe that's part of the problem. Maybe i should only be able to call a cell via role name if i provide both the role name and index (even for provisioned cell where the index is 0).

**Comment by maackle** [comment]
The difference is that the app UI can know about the role name without querying because it's defined by the app manifest, but you can never know a clone cell's handle without querying for it, because it's at least partially determined at its installation time. So it seems if you don't query, it makes sense to use role name, but if you have to query (as you must for clone cells), you might as well use the CellId.

**Comment by mattyg** [comment]
> Even if you use role name + index to refer to a clone cell, you still had to query to discover the index, so why not just use the CellId? The other difference is that rolename+id is shorter and a bit more human-friendly, which I can see as a benefit.

Yeah for me the big benefit of supporting both is just for interface consistency. From the app dev perspective I want to be able to work with any cell -- cloned or provisioned, in exactly the same way, unless there is a reason I need to dig into the unique features of the particular cell type. Otherwise it ends up pushing a bunch of conditionals up to the app layer. 

For example, the profiles ui client library takes a role name to determine which cell it should call the 'profiles' zome within. (https://github.com/holochain-open-dev/profiles/blob/a1a487c8d6a8fd9910ba9b3f26e47df0bf0d09ae/ui/src/profiles-client.ts#L17).

I guess every client library could take `RoleName | CellId` -- if they're just getting passed on to callZome anyway it takes either. Maybe that's better practice anyway.

**Comment by maackle** [comment]
> I guess every client library could take `RoleName | CellId`

I like that idea, seems clean and convenient

**Comment by mattyg** [comment]
I created a standalone issue for pulling common fields into a higher-level type here: https://github.com/holochain/holochain/issues/4378

I am renaming this issue to be specific to clarifying the role name for clone cells

**Comment by ThetaSinner** [comment]
@mattyg You were looking at the issues around this one, what should happen with this issue?

**Comment by mattyg** [comment]
I was keeping this as the canonical issue and closed the others as duplicates.

Though maybe I should replace this with a clearer one to reduce the noise. I'll make one with the solution proposed above, we can have some discussion around it, and see if it needs a design session.

**Comment by mattyg** [comment]
This issue is replaced by #4485 which outlines the problem and proposes a concrete solution.
