### ISSUE TITLE
[Enhancement] Make GetOptions available for get_links & get_links_details calls

### ISSUE THREAD

**Issue by mattyg** [holochain/holochain#3247]
Currently [GetOptions](https://docs.rs/hdk/0.3.0-beta-dev.29/hdk/prelude/struct.GetOptions.html#method.content) is only available for `get` calls. It is not available in `get_links` calls.

We should make this available for `get_links`  and `get_links_details` calls so we can specify to get the links only from our local cache, not hit the network.

**Comment by ThetaSinner** [comment]
Finding myself wanting this too, this is a relatively straightforward change compared to some other requests because there is example code to work off for `get`.

@maackle @neonphog @jost-s any objections to the HDK being updated to include this? Any volunteers? I can take a look if everyone is busy at the moment :)

**Comment by jost-s** [comment]
No objections. I can do it.

**Comment by jost-s** [comment]
> so we can specify to get the links only from our local cache, not hit the network.

It's not how the `GetOptions` strategies work at the moment and I think we need to clean that up. It's quite confusing and the two variants of the enum `GetOptions` don't fit together semantically.

In a `get_entry` or `get_action` request, the default strategy is `Latest`. If you're not the authority of the entry/action, it's attempted to be fetched from the network, together with its metadata (updates and deletes), and added to your local data. Then, or if you are an authority, it'll be returned based on locally available data.

For `Content` only the locally available data is considered at first and if you're an authority, the entry/action is returned based on whether it's available there or not. If you're not an authority, it'll fall back to what `Latest` does.

I find all that hard to understand and tricky to assess from a happ dev's point of view.

What should happen if you call `get_links` with `GetOptions::Content`? You want it to return only locally available links and not fetch from the network. That makes sense to me. But this option needs to be renamed and IMO split up into 1. fetch from network/local data and 2. fetch despite being authority.

**Comment by ThetaSinner** [comment]
I agree, the naming should be updated. I'm not so sure about the network behaviour. Going to the network when you're an authority in a small network should be pointless because you'll have had the data published to you, and if not then it'll get gossiped to you soon enough. In a bigger network, I think the question should be whether bypassing publishing/gossip is the right thing to do? That's the question I had when I looked at a bug in `get_links` anyway. I'm inclined to say no, don't go to the network, and let the existing sync mechanisms update your view of the world over time. That's the way that the `GetStrategy` is currently documented

**Comment by ThetaSinner** [comment]
Being stuck in app validation is actually an important point. I believe if you ignore the authority rules and go and do a fetch, you'll end up putting unvalidated content in your cache and therefore available to other parts of the code. That would be bad. If we're an authority for an op that is in app validation then we should definitely wait for it to finish that step.

>  "you should have it or will get it soon" is an unsatisfactory answer

I don't think so. The processing and network load of syncing ops is already quite significant. Actively going out and fetching things that are already on their way is going to make performance even more unpredictable. Especially if you get a user who refreshes their page a lot waiting for things. It's best that those front-end interactions don't cause Holochain to go off and do extra work where possible. When it's arrived and validated, it'll show up, that seems sensible to me.

---

Anyway yes, off topic a bit! I don't think that many people are aware of `Content` from the conversation we had in office hours, so maybe that should just become `Local` and never go to the network. Then `Latest` is a reasonable name but I'll happily approve a PR that proposes something better, and its behaviour doesn't really need to change I think?

**Comment by maackle** [comment]
> Currently it can be stuck in app validation, so you have it but don't have it.

Actually I think there's something else we can leverage here. Currently if you're attempting to get stuff from the network:

- If you *are not* an authority, you will fetch the data from an authority and put it in your cache, unvalidated.
- If you *are* an authority, you will only return data if you have validated and integrated that data yourself.

The authority case is stricter than it needs to be. If the two cases were symmetrical, then when you're an authority, you should be able to use your own data to respond to a `get` even if the data is in limbo, since this is equivalent to the unvalidated data that you would be using if you were not an authority -- then in both cases you're working with data served on someone else's authority.

**Comment by maackle** [comment]
Also this is a great motivation for integrating all network activity under the fetch pool. If we did that, then even authorities could issue a true network `get` to bump up the priority of fetching that one item, and it would have no negative or duplicate effect on retrieving the same data through gossip or publish.
