### ISSUE TITLE
[spike] measure Holochain's performance under real-world circumstances using HoloFuel

### ISSUE THREAD

**Issue by jost-s** [holochain/holochain#3409]
I think of it as a spike of exploring Holochain networking performance in general

motivation (why)
* measure Holochain's performance under real-world circumstances using HoloFuel as an example app

unclear
* are we going to mimic or actually use real-world circumstances?

**Comment by steveej** [comment]
conductor metrics:
* holochain's currently available influxdb metric
* data source for the Launcher's progress bar
* data source for the holochain-terminal CLI


choose frontend-agent execution framework and metrics:
* drive real UI with puppeteer?
    * consider: existing frontend metrics the real UI
* headless version of a holofuel user?
    * sketch a rust CLI that drives HoloFuel and collects metrics we want

metrics collection
* ensure the influxdb metrics are enabled
* choose a central point that can store all the metrics for the test
* ensure that the test runs are distinguishable, if the central storage persists over test runs

**Comment by steveej** [comment]
as discussed in a recent meeting a preliminary decision has been made to reuse TryCD in the short-term for this effort. 

Holochain team concerns:
* what other services and infrastructure do we need for HoloFuel tests?
* what happens if we drive up the load on the conductor? this won't be explicitly tested if we were to re-use the UI automation (puppeteer) tests
* ideally we have a tight feedback loop between the UI and conductor testing efforts. specifically it could happen that the UI tests surface unexpected behavior that we can then encode as a more specific test on the conductor side.
