### ISSUE TITLE
Simplify zome call signing

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/holochain#3425]
DEPENDS ON: https://github.com/holochain/holochain/issues/4391

Currently zome call singing relies on the exact serialisation of the ZomeCallUnsigned payload. Rework the mechanism to lift this restriction so that clients do not need to bundle our Rust code to get the serialisation right.

**Comment by ThetaSinner** [comment]
I'd like this to wait until after 0.3.0 because it affects all the clients and it's too much interruption when there's so much else going on. For 0.4.0-beta-dev.0 it is fair game :)

**Comment by jost-s** [comment]
The problem is that Holochain deserializes the zome call payload when processing the zome call, and in order to verify the signature, the payload is serialized and hashed again. The data to sign is the hash of the serialized fields of the zome call payload ([struct UnsignedZomeCall]()).

This process requires that the hash to be signed

In the JS client, there is a package for serializing the same https://github.com/holochain/holochain-client-js/blob/main/src/api/app/websocket.ts#L509-L524
