### ISSUE TITLE
Add CI check that checks that the correct dependency version is available for compilation

### ISSUE THREAD

**Issue by abe-njama** [holochain/holochain#3467]
Add a regression test that ensures that the correct dependency version is present otherwise a new release version is not published.

**Comment by ThetaSinner** [comment]
I'm not so sure about this. I don't like how many checks we have to have in place to catch the mistakes humans can make when we don't have a way to test that those checks keep working.

Any checks that we can write tests for I'm happy with, but otherwise I'd prefer to try and drill into the cause.

In this case the root cause actually had little to do with dependency management. It was using a Cargo feature that we already know breaks our automation and hoping for the best. Unsurprisingly it bit us.

To me the solution is to solve #3464 and write some tests around that. Then we'll be able to safely use workspace dependencies without these problems.

Maybe I can provide better motivation with this reasoning: When we fixed the dependency issue so that we were on the latest version and only had a single dependency on it, the problem persisted because we did a bad publish. 

Very much a human problem of deciding how comfortable we are with risk and so not something I'd like to address with tooling :)

**Comment by jost-s** [comment]
I don't have enough insight into this issue, but what Gregory is suggesting makes sense to me. It would be good to enhance the release automation to allow for workspace dependencies.

On the other hand, if there's a tool that handles our release, I'd prefer to adopt using that instead of writing and modifying our custom release automation tool.

**Comment by jost-s** [comment]
We'll create a simplified version of a release manager instead, which will be able to handle workspace dependencies.
