### ISSUE TITLE
Be able to warrant for forking

### ISSUE THREAD

**Issue by abe-njama** [holochain/holochain#3470]
https://chat.holochain.org/holo/pl/pnb8w5fgxtyx3kzaom63h1ojxc

Use case: HoloFuel app cannot detect chain forking / double-spends in validation code because  it can only use hash-bounded must_gets on agent chain data, and both forks will look valid from the perspective of either double-spent transaction. For HoloFuel to make its integrity guarantees, we have to be able to warrant for forking.

**Comment by maackle** [comment]
First of all I believe this depends on https://github.com/holochain/holochain/issues/3576

If that issue is about creating the Warrant type and making sure it propagates to the necessary authorities, then this issue is about defining the specifics of the ChainFork Warrant.

ChainFork can be automatically created by any authority which detects one: two actions by the same author with the same action_seq. Realistically Agent Activity (Chain) authorities are the ones best poised to do this.

## AC

- add ChainFork warrant type to Op
- as part of sys validation, chain authorities can author Warrants which get published and gossiped to other chain authorities (via the work already done in #3576)
- hook up [`AgentActivity::warrants`](https://github.com/holochain/holochain/blob/bf463d5306a1334ef6858f25b9596c463f23c6ad/crates/holochain_zome_types/src/query.rs#L122) with the real Warrant type
- make sure the AgentActivity output includes any ChainFork warrants held by this authority
