### ISSUE TITLE
Ensure TURN server is correctly configured

### ISSUE THREAD

**Issue by abe-njama** [holochain/holochain#3478]
Ensure TURN server is correctly configured (e.g. enough files/ports, trying to negotiate STUN first, sensible timeouts to drop connections, cli accessible for diagnostics, etc.) Maybe make an easy nix-shell image or docker container of a properly configured server for easy/experimental replication.

**Comment by steveej** [comment]
closing in favor of #3585

**Comment by steveej** [comment]
closing in favor of #3585

**Comment by steveej** [comment]
reopened becasue we need to maintain the TURN infrastructure for a while longer than initially expected when SBD started emerging.

**Comment by steveej** [comment]
@neonphog do you think there's anything for us to do here? my preference is to let the TURN infrastructure be as is until it can be phased out, and close this issue.

**Comment by neonphog** [comment]
@steveej - We should weigh the risks of running the patched version that can have smaller timeouts on the sessions. If we set them to 20 seconds instead of 10 minutes, that gives our servers 5X the capacity given the majority of the connections are not used.

If we are not comfortable with taking on that risk, then, yes, this story should be considered complete.

**Comment by steveej** [comment]
personally i'd rather not take that risk, because of the discouragement on parts of the coturn maintainers.

**Comment by steveej** [comment]
@abe-njama let's finalize this in our meeting tomorrow please.

**Comment by steveej** [comment]
this we're transitioning away from TURN this is no longer relevant
