### ISSUE TITLE
Ensure Holochain is reusing existing STUN/TURN connections rather than creating new ones

### ISSUE THREAD

**Issue by abe-njama** [holochain/holochain#3480]
Ensure Holochain is reusing existing STUN/TURN connections rather than creating new ones. (Why do we have so many connections registered on the TURN server between the same peers?)

**Comment by ThetaSinner** [comment]
Are we going to do this on 0.2 or 0.3? There's a good chance this is going to involve drilling down into tx5 and potentially even the Go code to understand the exact lifecycle of connections and we're on different versions of tx5 on 0.2 and 0.3. I suggest that we do this on 0.2 because that's where the issue currently is and needs resolving most urgently. I can then work forwards if I find a problem.

**Comment by ThetaSinner** [comment]
Answer: 0.2 for now, and if we find that the problem doesn't exist on 0.3 then we can assess the timeline for 0.3 and see what we can do about moving to it sooner than planned

**Comment by ThetaSinner** [comment]
As far as I can tell from Kitsune and tx5 code, everything is working as it should be. If there is a problem in code we depend on then I'd need to do some exploratory testing to see whether I can persuade two nodes to create multiple connections to each other. This next step has not been prioritised to be worked on yet.
