### ISSUE TITLE
Websocket security

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/holochain#3558]
Following on from #3460 to add `Origin` header checks on websocket connections, we need to make sure that app interfaces only accept connections from intended clients. That is, having passed the origin check for an app websocket, the client needs to authenticate.

To this end:
- [x] App interfaces can OPTIONALLY be bound to applications. If an app interface is bound to an application then it must only accept connections for that app. If the app interface is not bound to an application then it must accept any connection that passes the origin check and provides valid authentication.
  Done on #3622
- [x] Add a new option to the admin interface which allows authentication tokens to be created:
  - Token values must be unpredictable and unlikely to repeat.
  - Bound to an application id
  - Have an expiry that is specified as part of the request
  - By default tokens will work once, then be discarded by Holochain. Allow an option on this request to make tokens re-usable up to their expiry.
  Done on #3622
- [x] Add a new option to the admin interface to remove authentication tokens. This is less critical than being able to create them and they will expire anyway but for re-usable tokens this is effectively a way to revoke them.
  Done on #3765
- [x] Update the websocket connection checks so that authentication tokens are required for connections to app interfaces to be established.
  Done on #3622
- [x] Update the conductor/websocket implementation so that it operates in terms of connections instead of websockets. 
  Done on #3643
- [x] If possible, as part of the refactor to operate on connections instead of websockets, ensure that when we try to send on a websocket that has been closed by the client, we drop that connection on the server. This avoids endless logs about sending on closed connections! See #3350
- [x] Add functional tests for Holochain that demonstrate the intended usage patterns for `Origin`s, app binding for app interfaces and authentication tokens.

**Comment by matthme** [comment]
> If the app interface is not bound to an application then it must accept any connection that passes the origin check and provides valid authentication.

Can a connection established in that way still only make calls related to the app id for which authentication was provided (assuming that authentication is always bound to an app id)?

**Comment by guillemcordoba** [comment]
In the cases for local holochain runtimes (moss, launcher, etc.), I don't feel the need to do the whole handshaking with tokens around connections, as the runtime must still provide lair client signature to the frontend to allow the app to sign zome calls, so wouldn't it be easier to just request the signature of some random nonce? This would mean that we don't have to manage a separate token with all its own separate state and lifecycle.

**Comment by matthme** [comment]
If I understand your proposal correctly I think it would not work for browser extensions or alike since in that case which keypairs are authorized to sign zome calls are stored as cap grants at cell level and could therefore probably not be used to validate app websocket calls (which are not at cell level, apart from the callZome request). Maybe that's already implied when you say "in the cases of local holochain runtimes" but thought it's worth mentioning anyway.

**Comment by guillemcordoba** [comment]
Yes I understand that, and that's what I meant. I wasn't clear on how this proposal addresses browser extensions, but I just thought of a way to support them with a runtime using deep-linking, so now I see the value of having the tokens. But then in that case the zome calls won't be signed by lair, which is fine, I guess we are saying "let's move all authentication to the connection handshake level" which I'm all for. 

I still think it'd be worth having the signing mechanism because in the case of runtimes it simplifies the handshake and management of authentication, "oh it's just you". That or the @holochain/client could just make all calls go through IPC so that instead of just signing the zome calls, the runtime _actually_ routes the zome calls to the conductor because it has the conductor handle in memory. But then signals don't work...

**Comment by ThetaSinner** [comment]
> Can a connection established in that way still only make calls related to the app id for which authentication was provided (assuming that authentication is always bound to an app id)?

Yes, connections are always bound to an app. If you want to talk to multiple apps then you need to coordinate that in your application by opening multiple connections.

**Comment by ThetaSinner** [comment]
> as the runtime must still provide lair client signature to the frontend to allow the app to sign zome calls

This is only for zome calls though, the rest of the app interface is still accessible if we don't add a check of some kind at that level. I agree with this sentiment of not having to do two authentication steps for zome calls and I have raised it myself. My preference would be to hide the zome call signing for authenticated connections... But that would have to be a future step because that's a fairly major change.

One way or another, this isn't the end of changes to the app interface but I do think that we need to make a change like this so that people can run HF on Launcher without having to worry about rogue websites messing with Holochain.

**Comment by ThetaSinner** [comment]
Best guess having made a start on this to see what needs doing, is that it's about 5 days of work including testing. Then we'll need to do client and trycp/tryorama updates etc

**Comment by ThetaSinner** [comment]
Note that #3765 did not make it into 0.3.x and will only be available in 0.4.x

**Comment by guillemcordoba** [comment]
Are tokens persisted across conductor restarts?

**Comment by ThetaSinner** [comment]
They are not. The main reason being that there's no way to list issued tokens so it would be rather difficult to keep track of what has been issued and work out when to revoke tokens if we made them persistent. Not persisting tokens seemed like a good balance of simple and safe.

**Comment by guillemcordoba** [comment]
:+1: that makes sense
