### ISSUE TITLE
Ability to detect if my chain is locked

### ISSUE THREAD

**Issue by abe-njama** [holochain/holochain#3604]
As an HDK function, which is especially useful before countersigning (it's fine for other commits to find out only on failure)

- Could bake this into countersigning session creation but maybe more ideal to check explicitly

This is meant to improve HoloFuel performance.

Original thread: https://chat.holochain.org/holo/pl/kaznopreyibr5yzm9u56ygzura

**Comment by neonphog** [comment]
This feels like the classing filesystem problem where you shouldn't check to see if a file exists before creating it, because it might be created after you check but before you do something with it.

It may be correct that there is no function for checking chain locked. It may be preferable to just try the operation and get an error if the chain is currently locked.

**Comment by jost-s** [comment]
There are a few steps before initializing a countersigning session that include making a remote call to a counterparty that need to be run. With a prior call to check for a chain lock, these preliminary steps could be saved.

**Comment by jost-s** [comment]
Can be achieved by calling `AppRequest:GetCountersigningSessionState`
