### ISSUE TITLE
Ability to initialize lmdb environment automatically

### ISSUE THREAD

**Issue by zippy** [holochain/holochain#411]
Currently when the conductor starts up if there is no environment at the directory specified in the config file, the conductor panics with:

```
FATAL PANIC PanicInfo {
    payload: Any,
    message: Some(
        Could not initialize Conductor from configuration: DatabaseError(EnvironmentMissing("/var/lib/holochain-rsm/databases/conductor")),
    ),
    location: Location {
        file: "crates/holochain/src/bin/holochain/main.rs",
        line: 143,
        col: 5,
    },
}
```

We also need a non-interactive way to create the environment.  I would suggest that in this case (i.e. valid config file), it simply creates the environment at the specified path.

**Comment by peeech** [comment]
I agree with it. Interactive mode is building a configuration file. Once config file is there and valid conductor should make things work with settings provided by this file. 

So the change would be that instead of throwing a DB error it would detect that there's no file at that location and initialize db there.
