### ISSUE TITLE
[Enhancement] Improve ergonomics of `send_remote_signal` types

### ISSUE THREAD

**Issue by mattyg** [holochain/holochain#4422]
`send_remote_signal` takes an `ExternIO::encode` that is not necessary in other similar HDK functions.

**Comment by cdunster** [comment]
@guillemcordoba, I believe that this issue was created from a list of requests from you: #889.
Do you know if it is still a problem? I see that `send_remote_signal` in the HDK already accepts a generic type instead of `ExternIO`: https://github.com/holochain/holochain/blob/develop/crates/hdk/src/p2p.rs#L148
Thanks :slightly_smiling_face:

**Comment by guillemcordoba** [comment]
Not a problem anymore!
