### ISSUE TITLE
How to integrate with a c++ single executable?

### ISSUE THREAD

**Issue by fire** [holochain/holochain#656]
Does holochain have a story for integrating with c++?

**Comment by pdaoust** [comment]
I did hear about a community member doing C-bindings for Holochain -- you're looking to be able to embed an entire Holochain runtime into your C-based application, right? I'll get back to you with more information as soon as I can track down that person :)

**Comment by pdaoust** [comment]
Okay, I was a little off in what I remembered -- turns out that what @Connoropolous had done was use the conductor (the Holochain runtime) [in a standalone Rust binary](https://github.com/Sprillow/cmdchatter/blob/master/src/main.rs). If it's that easy to use it as a library, maybe it's equally easy to just compile it into a library and link to it from a C application in the same way? But AFAIK there are no official stories in our backlog yet. What's your usecase?

**Comment by fire** [comment]
I was thinking about your usage described here. So like a remixable keybase.

![image](https://user-images.githubusercontent.com/32321/109086818-28c99f80-76c1-11eb-80da-023cb90b283f.png)

**Comment by ThetaSinner** [comment]
Hi @fire, I'm not following the link from the question to the whitepaper page about membrane proofs. Could you elaborate on how having a C++ friendly interface helps here?

I think the approach @pdaoust is suggesting is probably a good way to go. The [launcher](https://github.com/holochain/launcher) does something similar by distributing the holochain binary and running it as a separate process.
Though that would require a C++ client library if you want to talk to the running holochain, which isn't something that's on the roadmap as far as I'm aware. It's Rust and Typescript/Javascript for now. I don't think that's what you were after originally though so maybe I'm on the wrong track here!

**Comment by fire** [comment]
Sorry I have forgotten everything about this conversation.

I was looking for something to integrate into a single binary through c ffi, but then my project put a hold on crypto related integration.

**Comment by ThetaSinner** [comment]
Thanks for coming back to me @fire!

I think the answer I gave above is the best one I can provide for now. Holochain doesn't expose a C interface for FFI integration and integration is currently done with processes rather than embedding.

I'll close this for now but if you come back to this problem please do reach out and see what we can do to enable you to integrate the way you need to
