### ISSUE TITLE
Expose `HoloHashB64` in `hdk`

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#682]
So I just found out that `HoloHashB64` exists. It seems ideal to use as return types for a lot (a lot) of applications. So it just seems like a good idea to expose them in th hdk prelude, which I don't see now.

@thedavidmeister maybe you have already considered it and there is a good reason why not to do this?

**Comment by pospi** [comment]
@thedavidmeister and I went back and forth with this sort of thing a *lot* in the context of record identifiers and msgpack type parsing at the API boundary. There are a few concerns here and the consensus we came to was to not do this, for the major con outweighs the pros:

**Major con:** performance. Holochain's protocol was designed to send binary-over-the-wire in order to speed up various parsing and memory optimisation things and basically allow data to "stream through" networks and nodes with as little processing as possible. Encouraging app developers to string-encode IDs at their zome API boundary is also encouraging developers to double-serialize their ID types in a way that is unnecessary for Holochain nodes communicating with each other directly. Ergo, unnecessarily inefficient.

**The pros** are basically about type universality between languages, but even there I think there are actually necessary edge-cases between systems which *have* to enforce some kind of type loss at the boundary in order to be "universally callable".

One situation this shows up in [is identifiers](https://github.com/holo-rea/holo-rea/blob/5ce59d3/modules/vf-graphql-holochain/connection.ts#L54), the other is [with dates](https://github.com/holo-rea/holo-rea/commit/b0771d4a88b2420e173d69fdd3f1674084d2e8c5). In both cases, the ideal handling would seem to be as indicated in the linked code refs&mdash; double-handling of special datatypes at the application API boundary *on the side of the client application*. This is because "Rust to Rust" is the layer to optimise for; "Rust to JS" is where any type conversion inefficiencies between different languages should be addressed. It's also reasonably common convention in various browser-side HTTP API libraries.

**Comment by thedavidmeister** [comment]
for more context and to show that its a non-trivial problem, here's an example effort at structuring data to represent and preserve types between languages - https://github.com/cognitect/transit-format

**Comment by pospi** [comment]
Thanks for this detailed response, highly illuminating. I think I have some answers on what an ideal implementation for this looks like at the API boundary which I want to experiment with a bit more before discussing here.

RE **Dates** *(which were a slight diversion sorry)*-

So *"binary data *is* universal"*- agree; but there are layers going on here with `@msgpack/msgpack` which may not be ideal. @artbrock tells me this module choice was off-the-cuff and research into alternative JS client libraries might be worth some time. Reason I suggest this is that *some* type-specific handling for `Date` seems to be happening internally in `@holochain/conductor-api` or its dependencies, best-guesses are that `Date` is being serialised the same as any custom `Object` sub-class and that the Rust host side has no mapping for this class. Potentially this is configurable, or there are alternative libs in which it is.

**Comment by pospi** [comment]
I think I have a proof of concept for this that gives us a "best fit" between Holochain and the browser environment when it comes to ID handling (ping @guillemcordoba).

**In the Rust layer** I've defined [some new tuple type wrappers](https://github.com/holo-rea/holo-rea/blob/6c68327/lib/hdk_type_serialization_macros/src/lib.rs#L53) that I generate for all my identity structs by [defining different types](https://github.com/holo-rea/holo-rea/commit/20a43331d5162d0987510538b72c665544d226f5) for referring to records locally vs from outside the cell. My framework still uses simple `EntryHash` & `HeaderHash` to operate on data- the cell data gets stripped away at the API interface.

For records managed inside the local cell, [I inject](https://github.com/holo-rea/holo-rea/commit/774b6f7a257daca49931aa2f4d15643cba1aa23c#diff-f50acfcf5160740e7ed069d04f2783316dc651f5fdcdb16d1015f8b6b54f37acR80) the `DnaHash` prior to transmission and define all my external structs with eg. `AgreementAddressRemote` as fields instead of `AgreementAddress`.

Fields referencing other records should also use the `*Remote` types in `Entry` storage structs, such that a `DnaHash` can be used to easily determine the remote cell to be called in order to interact with the referenced entry. This has implications for indexing strategies that will require some time to work through.

Result: (hopefully) simple record identity handling via performant, compacted binary-serialised format. Please advise if you see any glaring issues with this approach! Potentially also functionality that hdk may want to provide in future.

--------

**In the JavaScript layer** I did look into an alternative experiment of adding `CellId`s [on the client side](https://github.com/holo-rea/holo-rea/commit/e375a9b4cd870f9462f61d602ae680a50a095306#diff-455ca9c2e97f4cd852f5ccca52b9a1e465168ae03ed1bee558d7a61ba91b5da5R184), but that doesn't pan out since zomes might need to contain the identities of entries in foreign zomes. So having `DnaHash` as contextual with each ID seems necessary and unavoidable.

I've stayed away from including `AgentPubKey` in the identifying information since I imagine the public key through which two different agents access the same information will differ. This means that in cases where a conductor operating multiple agents with access to a resource on a single `DnaHash` it may be difficult to determine which cell to query; but if this is the case then it's likely that the application UI will need to be aware of that.

Result: simple-ish API type handling that in many cases can leave the resultant type of `[Buffer, Buffer]` untouched; or run through [string serialisation](https://github.com/holochain-open-dev/core-types/blob/591df32/src/utils.ts#L9) if needed for tooling requiring ID primitives (such as GraphQL).

**Comment by thedavidmeister** [comment]
@pospi yes i'm keen to review how messagepack can be handled better in javascript, and i'd even be totally fine with pushing for typescript if that helped to give the serialization layer the context it needed to reliably handle more data 'out of the box'

next time i get around to a HDK sweep i'll have this as a high priority if nobody else solves it first :)

**Comment by artbrock** [comment]
Curious if this has been addressed with the string-encoding feature you can specify in your DNA's Cargo.toml like this:
```
holo_hash = { version = "0.0.2-alpha.1",  features = ["string-encoding"] }
```
So when you use to_string on a holohash you get base64url encoded strings.  

Does that address this issue?

**Comment by guillemcordoba** [comment]
Oh yes, actually this is not really an issue but a "feature request".  You have always been able to import the holo_hash crate and use the B64 hashes from there. Re-exporting the B64 hashes from the `hdk` crate would enable their usage without having to use the holo_hash, which I don't think zomes need otherwise.

So, in summary, this is just for facilitate its usage and make it easier for new devs.

**Comment by guillemcordoba** [comment]
This is done! Thanks :D
