### ISSUE TITLE
Volume of outbound traffic (from holochain service in holoport) triggers home internet security blocking functionality to turn on

### ISSUE THREAD

**Issue by JettTech** [holochain/holochain#797]
Multiple times every hour over the past week I have received these security warning messages due to the volume of outbound connections from the holochain service in the hpos.  

I am using at&t fiber, which includes a new security software, ActiveAmour, which auto detects and prevents perceived network security threats.  In order to overcome this block, I have to either turn off the hpos, periodically restart the holochain sevice, or temporarily disable the inbuilt at&t security system.

Here is a screenshot of the received messages:
![image](https://user-images.githubusercontent.com/30459942/119928139-9c897b80-bf40-11eb-9ba1-a9416cdc8150.png)

**Comment by artbrock** [comment]
Hey Lisa,

Can you re-test this since the gossip updates merged over the past weeks? Also sharding should land in the next weeks which will obviously help.

Also, can you clarify where this ActiveArmour app runs?  Is it running on your local PC? Or on the router?

Also, were you running scalability tests? And running a HoloPort? or was this happening during dev testing?

-art

**Comment by steveeJ** [comment]
@JettTech i assume this has been resolved as this issue has been stale for a while. please feel free to reopen this again.
