### ISSUE TITLE
`hdk::x_25519_x_salsa20_poly1305_decrypt()` hangs on Error

### ISSUE THREAD

**Issue by ddd-mtl** [holochain/holochain#831]
`hdk::x_25519_x_salsa20_poly1305_decrypt()` hangs when decryption fails. I have a simple tryorama test where I encrypt and decrypt some vec, and if a give the wrong keys (by inverting sender and recipient), the function call never returns, and I get a timeout.

I was told lair currently doesn't do error responses, which makes the encryption almost unusable as there is no way to figure out whats the issue when a decryption fails.

**Comment by artbrock** [comment]
Damien also posted this find about where: 
> The hdk doc has inverted the arguments. It states fn x_25519_x_salsa20_poly1305_decrypt(recipient, sender, data) but what actually works is  fn x_25519_x_salsa20_poly1305_decrypt(sender, recipient, data)

**Comment by thedavidmeister** [comment]
oof, it's not just the docs

```
impl X25519XSalsa20Poly1305Decrypt {
    pub fn new(
        sender: X25519PubKey,
        recipient: X25519PubKey,
        encrypted_data: XSalsa20Poly1305EncryptedData,
    ) -> Self {
        Self {
            sender,
            recipient,
            encrypted_data,
        }
    }
```

this is a bug, the `new` method is reversed order relative to everything else

**Comment by thedavidmeister** [comment]
https://github.com/holochain/holochain/pull/874

**Comment by thedavidmeister** [comment]
so i'm wondering why the tests did not pick this up, and i think it is because either the sender or receiver can decrypt anything encrypted with this algorithm

which means that if the keystore has both private keys in it, the decryption will still work even with the parameters swapped

but in the wild that's not the case, so the bug shows up when the keystore only has the recipient private key in it with the backwards parameters

at least, i think that is what is happening here :thinking:

**Comment by abe-njama** [comment]
@ddd-mtl This issue was resolved in this [PR](https://github.com/holochain/holochain/pull/874). I'd like to proceed to close this issue, once you confirm that the issues is actually resolved i.e. you're not encountering the issue anymore.

**Comment by ddd-mtl** [comment]
I confirm this issue has been resolved. Thanks for the follow-up
