### ISSUE TITLE
[Feature discussion] Ability to do `call` from within validation rules

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holochain#849]
Hi :) So I know this will be a somewhat controversial topic, so I wanted to start the discussion in an issue where we can keep track of the points.

## Desired feature:

**I would like to be able to do `call` to other DNAs from within validation rules**.

Provided, this will make the caller DNA **dependent** on the callee. I don't think this is bad per se (every DNA depends on deepkey in a way), just needs careful handling on behalf of developers.

## Use cases

Right now, I can see these 2 use cases very cleary, I'm sure there will be others:

- Verify whether a signature was done with a key that has been revoked. In this case I would want to `call` deepkey to verify that. It could be argued that this should rather be done via the "conductor services", one of which is deepkey.
- In the compository, and also in hREA, we would like to have a "membrane DNA", that holds the membrane for the group, and the roles inside that group. Complementary DNAs can be installed that refer to that DNA to validate whether an agent can join the network, or if they can create a certain type of entry there. The alternative would be to duplicate the roles entries in all the smaller DNAs, with the overhead and inconsistencies that this could bring.

Feedback is welcome and appreciated :)

@artbrock @pospi @thedavidmeister

**Comment by pdaoust** [comment]
One thought: We talk about explicit dependencies + `must_get_*` as a way of guaranteeing validation determinism. In order to carry the same expectations and promises across the DNA/DNA boundary, what about... I'm not sure... but it would probably look something like a `must_get_from_other_cell` host function? (ignore the ugly name) Then we're not forced to wonder about non-deterministic behaviour in the callee; the conductor can guarantee it for us.

Otherwise, perhaps marking an extern as deterministic (with appropriate permissions for host functions) could be another, more versatile, alternative.

I don't know how that meshes with your use cases @guillemcordoba -- my suggestion would definitely enforce "valid as at (logical timestamp)" constraints. But maybe that's what's necessary for determinism?

**Comment by artbrock** [comment]
I don't even love the idea of calling across zomes in validation, much less DNAs. I am not sold on this for a number of reasons. The main one being that a DNA becomes non-functional without a different DNA. I think we have a problem of units of composability and of separation of concerns with that kind of dependency... DNAs that were in fact never separable in the first place.

Clarification: I have no problem with DNAs calling into and reading data from other DNAs in zome functions and in constructing entries, but in VALIDATING entries we have a problem.

First let's address your two use cases:

1. Deepkey is set up to be a conductor service exactly so that every DNA can just ask the conductor. You might even run a different version of Deepkey or your own key manager. As long as the conductor service is bound to it, then we're good. 

2. Membranes... Ideally, you should provide a self-evident membrane proof for joining a DNA... Not only can you not talk to the DHT you're joining during that process (because you're in the process of still creating your DHT address and it hasn't been accepted yet by others), but you're certainly not going to be able to rely on querying other DNAs when you haven't been accepted yet to the one your joining.

3. Roles (further extension of #2). In the scenario of wanting to define roles and identify users who hold those roles, I can understand wanting to bridge to this sort of look up system during validation. I'll need to think about this one more because although I don't like it, at least  the desire this case is understandable. I'll think about other less risky/compromising approaches.

**Comment by guillemcordoba** [comment]
Thanks Art, I like the pushback! I somewhat knew that this was not going to be very popular, so I'm all for the alternative approaches. I just want to keep these use cases in mind so that we get good and flexible primitives that we can use.

**Comment by guillemcordoba** [comment]
So @artbrock thinking about the membrane proof... Let's see if a concrete use-case helps us in clarifying if this is even a good design for a hApp, and if it is, how it should be architected or how core has to change to accommodate it.

Let's say I have a google drive clone happ, with a private membrane by invitation (you have to be invited by someone already inside the DNA to be accepted). I have these 3 DNAs:

1. Lobby: here you ask to be invited in the main drive DNA, by gathering the appropriate countersignatures. 
2. Main DNA: here you have the structure of folders, the write and sharing permissions, also maybe the roles. Here the membrane validation rules are coded like this:
    - The membrane proof should be a struct like this:
```rust
          struct InvitationProof {
              invited_agent: AgentPubKey,
              timestamp: Timestamp,
              invited_by: AgentPubKey,
              invited_to: DnaHash
          }
          struct SignedInvitationProof {
              invitation_proof: InvitationProof,
              signature: Signature
          }
``` 
    - And the `validate_create_agent` something like:
      - Validate the signature of the invitation proof.
      - Validate that the agent trying to enter is the one in the `invited_agent` field.
      - Validate that the DNA hash is the one that the agent is trying to enter.
      - Do a `get` with the `invited_by` `AgentPubKey` and verify that agent is already there in the network.
3. File-storage DNA: as we don't want all the nodes to be tasked with holding the load of the files, only the nodes that have this 3rd DNA installed are the ones holding the actual files.

Now the question is: what validation rules should be encoded in the 3rd DNA? Obviously, not every member of the second DNA will be there, so the last step of the membrane validation rules won't really work... But you don't want any outer agent to be able to enter without first being invited by someone inside the 2nd DNA. 

- Is there any self-validating membrane proof that I'm not seeing that would allow to have the appropriate membrane in the 3rd DNA? 
- Is this not a good architecture? Seems like a lot of use cases will end up having a similar problem.
- Or should core implement some way around this?

 As I said before, just exploring different use-cases to be sure that core has what we need in order to implement the really cool patterns that we all want Holochain to enable :D
